"""The CNCF wall: grid scaling, the committed record, and the authored card.

The wall is drawn by scripts/build_cncf_wall.py from stories/cncf-projects.json
(GENERATED by scripts/sync_landscape.py) and burned by tools/plate.py, which
must NOT draw it. The title and footer are authored in
chapters/III-mrbobbytables.md. Everything here is offline: the sync's network
is exercised only through resolve(), which takes the landscape as a fixture.
"""

import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

import build_cncf_wall as wall  # noqa: E402
import sync_landscape as sync  # noqa: E402

DATA = REPO / "stories" / "cncf-projects.json"


# --- the grid ---------------------------------------------------------------


def test_the_seed_set_lays_out_three_over_two():
    cols, rows = wall.grid_shape(5, 1520, 660)
    assert (cols, rows) == (3, 2)


def test_the_grid_scales_to_a_full_landscape():
    """The owner expects lots of logos over time."""
    cols, rows = wall.grid_shape(60, 1520, 660)
    assert cols * rows >= 60
    assert cols >= 8 and rows >= 5  # ten-ish across, not one long row


@pytest.mark.parametrize("n", [1, 2, 3, 4, 7, 9, 16, 100])
def test_every_count_fits_its_grid(n):
    cols, rows = wall.grid_shape(n, 1520, 660)
    assert cols * rows >= n
    assert (cols - 1) * rows < n or n == 1


def test_a_lone_last_cell_rebalances_upwards():
    # 4 in a 3+1 shape reads as a mistake; it should go 2x2.
    assert wall.grid_shape(4, 1520, 660) == (2, 2)


# --- the render -------------------------------------------------------------


def _projects(n=5, with_logos=False):
    return [{"id": f"p{i}", "name": f"Project {i}",
             "logo_png": "assets/cncf-logos/nope.png" if with_logos else ""}
            for i in range(n)]


def test_the_wall_renders_full_frame_with_title_and_footer():
    img = wall.render_wall(_projects(), "CNCF Projects to Help Your Agents",
                           footer="landscape.cncf.io")
    assert img.size == (1920, 1080)
    assert img.mode == "RGBA"


def test_missing_artwork_never_drops_the_name():
    """A project whose logo did not rasterize still takes its cell."""
    img = wall.render_wall(_projects(with_logos=True), "Title")
    assert img.size == (1920, 1080)  # rendered, not raised


def test_sixty_projects_render_inside_the_frame():
    img = wall.render_wall(_projects(60), "Title")
    assert img.size == (1920, 1080)


# --- the committed record ---------------------------------------------------


def test_the_record_matches_the_curated_set_in_order():
    """The wall's order is the owner's; the generated record must follow
    vocab/, never its own history."""
    import yaml

    curated = yaml.safe_load(
        (REPO / "vocab" / "cncf-projects.yaml").read_text())["projects"]
    doc = json.loads(DATA.read_text())
    assert [p["id"] for p in doc["projects"]] == curated
    for p in doc["projects"]:
        assert p["name"] and p["logo_png"]
        assert (REPO / p["logo_png"]).exists(), f"{p['id']}: artwork missing"


def test_the_seed_set_is_the_five_the_owner_named():
    doc = json.loads(DATA.read_text())
    assert [p["name"] for p in doc["projects"]] == [
        "Lima", "Kuasar", "Confidential Containers",
        "Inclavare Containers", "WasmEdge Runtime",
    ]


# --- the sync's resolution (network mocked by fixture) ----------------------


FIXTURE = {
    "items": [
        {"id": "runtime--container-runtime--kuasar", "name": "Kuasar",
         "homepage_url": "https://kuasar.io/", "logo": "logos/abc.svg"},
        # The duplicate-name trap: matching by NAME would credit the variant.
        {"id": "runtime--container-runtime--kuasar-wasm",
         "name": "Kuasar (Wasm)", "homepage_url": "", "logo": ""},
    ],
}


def test_resolution_is_by_id_never_by_name():
    projects, unresolved = sync.resolve(
        ["runtime--container-runtime--kuasar"], FIXTURE)
    assert not unresolved
    assert projects[0]["name"] == "Kuasar"
    assert projects[0]["homepage_url"] == "https://kuasar.io/"


def test_a_vanished_project_is_recorded_not_fatal():
    projects, unresolved = sync.resolve(["gone--nowhere--nothing"], FIXTURE)
    assert projects == []
    assert unresolved and "gone--nowhere--nothing" in unresolved[0]["what"]
    assert unresolved[0]["automatable"] == "no"


# --- the plate and the outro agree ------------------------------------------


def test_the_wall_plate_carries_the_authored_copy():
    doc = json.loads((REPO / "stories" /
                      "yt_curse_of_osiris_opening_cinematic-fixed-plates.json")
                     .read_text())
    plate = next(p for p in doc["plates"] if p["id"] == "cncf-wall")
    assert plate["kind"] == "logowall"
    assert plate["title"] == "CNCF Projects to Help Your Agents"
    assert plate["footer"] == "landscape.cncf.io"
    assert plate["copy_source"] == "owner_supplied"


def test_the_wall_sits_inside_the_outro():
    """The slide must be up only while the picture is dark: on or after the
    darken, and over before the fade swallows the frame."""
    from tools.redact import kept_range
    from tools.search import load_segments

    outro = json.loads((REPO / "stories" /
                        "yt_curse_of_osiris_opening_cinematic-outro.json")
                       .read_text())
    doc = json.loads((REPO / "stories" /
                      "yt_curse_of_osiris_opening_cinematic-fixed-plates.json")
                     .read_text())
    plate = next(p for p in doc["plates"] if p["id"] == "cncf-wall")
    video_end = max(float(s["end_sec"]) for s in load_segments(REPO / "segments")
                    if s.get("video_id") == "yt_curse_of_osiris_opening_cinematic")
    redactions = json.loads((REPO / "redactions" /
                             "yt_curse_of_osiris_opening_cinematic.json")
                            .read_text())["redactions"]
    start, end = kept_range(redactions, video_end)
    kept_dur = end - start
    assert plate["at"] >= outro["darken_at"]
    assert plate["at"] + plate["dur"] <= kept_dur + outro["extend"]
