#!/usr/bin/env python3
"""Every word in the programme, in the order the audience hears it.

THIS FILE IS AN OUTPUT. It is generated so the whole show can be read in one
sitting -- for pace, for repetition, for a line that lands wrong three acts
after the one it was written in. Editing it changes nothing on screen: each
line here says which chapter file it came from, and that is where a copyedit
goes.

    python3 scripts/generate_full_script.py --write
    python3 scripts/generate_full_script.py --check

Act II is the one act whose pills are not in a chapter file yet -- they are
generated from megacut-relative constants inside
``scripts/build_efmb_plates.py`` -- so its lines are read from its committed
manifest instead, and marked as such. That mark is the punch list: when act
II migrates, the mark goes.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools import chapter_md  # noqa: E402

OUT = REPO_ROOT / "chapters" / "full-script.md"

# Acts whose copy is NOT in a chapter file, read from their manifest instead
# so the read-through is complete. `where` is where a copyedit actually goes.
UNMIGRATED = {
    "II": {
        "manifest": "stories/02-endless-forms-plates.json",
        "programme_start": 283.800,
        "where": ("scripts/build_efmb_plates.py -- except the two red "
                  "splashes, which are in chapters/II-endless-forms.md"),
    },
}

HEADER = """<!-- GENERATED by scripts/generate_full_script.py -- do not edit. -->

# The whole show, read straight through

Every authored word in the programme, in the order the audience hears it.
**Nothing here is edited.** Each block names the file its lines live in; that
is where a copyedit goes, and this page is regenerated from it with
`python3 scripts/generate_full_script.py --write`.

Timecodes are **programme** time -- where the line falls in the whole cut,
not in its own act.
"""


# Every field that puts words on screen, in reading order. A card with
# several of them -- an eyebrow over a name over a message -- is read out in
# full: showing only the first would quietly drop two thirds of a birthday
# card from the read-through, and a line missing from a script is a line
# nobody notices is wrong.
COPY_FIELDS = ("text", "title", "label", "eyebrow", "name", "body", "names",
               "detail")


def speech(plate):
    """The words a plate puts on screen, as one line, or None if it puts none.

    A nameplate's name is deliberately NOT speech: nobody says it, and
    listing it here would read as dialogue attributed to a real person.
    """
    if plate.get("copy_source") in chapter_md.DERIVED_COPY:
        return None
    said = []
    for key in COPY_FIELDS:
        value = plate.get(key)
        if isinstance(value, list):
            value = " / ".join(str(v) for v in value)
        if isinstance(value, str) and value.strip():
            said.append(value.strip())
    return " / ".join(said) or None


def who(plate):
    """Who the line belongs to on screen, or an empty string for a card."""
    return plate.get("speaker") or plate.get("role") or ""


def act_lines(act):
    """(programme seconds or None, speaker, words) for one chapter file."""
    chap = chapter_md.chapter(act)
    plates, _ = chapter_md.entries(act)
    out = []
    for plate in plates:
        words = speech(plate)
        if words is None:
            continue
        at = plate.get("at")
        out.append((None if at is None else at + chap.programme_start,
                    who(plate), words))
    return out


def unmigrated_lines(spec):
    path = REPO_ROOT / spec["manifest"]
    if not path.exists():
        return []
    plates = json.loads(path.read_text(encoding="utf-8")).get("plates", [])
    out = []
    for plate in plates:
        words = speech(plate)
        if words is None:
            continue
        out.append((plate.get("at", 0.0) + spec["programme_start"],
                    who(plate), words))
    return out


def collect():
    """Every act's lines, ordered by where the act starts in the programme."""
    blocks = []
    for act, chap in chapter_md.discover().items():
        if act in UNMIGRATED:
            # Act II's chapter file authors two of its plates and its builder
            # generates the rest, and BOTH end up in the manifest. Reading the
            # manifest is the complete account; reading the chapter file too
            # would print those two splashes twice.
            continue
        lines = act_lines(act)
        if lines:
            blocks.append((chap.programme_start, act,
                           str(chap.path.relative_to(REPO_ROOT)), lines))
    # An untimed chapter has no clock, so it has nothing to sort by. It says
    # where it falls in the running order for reading purposes only.
    for act, spec in UNMIGRATED.items():
        lines = unmigrated_lines(spec)
        if lines:
            blocks.append((spec["programme_start"], act, spec["where"], lines))
    blocks.sort(key=lambda b: (b[0], b[1]))
    return blocks


def render(blocks):
    out = [HEADER]
    for _, act, where, lines in blocks:
        out.append(f"## {act}\n")
        out.append(f"Edit in `{where}`.\n")
        for at, speaker, words in lines:
            stamp = "        " if at is None else chapter_md.format_tc(at)
            said = f"**{speaker}** — {words}" if speaker else words
            out.append(f"- `{stamp}` {said}")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="write chapters/full-script.md")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file is stale")
    args = ap.parse_args(argv)

    text = render(collect())
    if args.write:
        OUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUT.relative_to(REPO_ROOT)}")
        return 0
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if current == text:
        print(f"{OUT.relative_to(REPO_ROOT)} is current")
        return 0
    print(f"{OUT.relative_to(REPO_ROOT)} is stale -- regenerate it with "
          "`python3 scripts/generate_full_script.py --write`", file=sys.stderr)
    return 1 if args.check else 0


if __name__ == "__main__":
    raise SystemExit(main())
