#!/usr/bin/env python3
"""Sync the curated CNCF project set with the CNCF landscape.

The SELECTION is curated -- `vocab/cncf-projects.yaml`, in display order, by
landscape id. Everything else is landscape data: this pulls
https://landscape.cncf.io/data/full.json, resolves each curated id to its
display name, homepage and logo, downloads the logo artwork, and writes the
generated record the wall renders from:

    stories/cncf-projects.json     generated -- never hand-edit
    assets/cncf-logos/<id>.png     the artwork the slide composits

    python3 scripts/sync_landscape.py            # report drift, change nothing
    python3 scripts/sync_landscape.py --write    # refresh the record + artwork
    python3 scripts/sync_landscape.py --check    # exit non-zero on drift

DEGRADE, NEVER BLOCK: a curated id the landscape no longer carries is recorded
in `unresolved` and the rest of the set still syncs. `--check` fails on it,
because a vanished project's logo on screen is a claim that needs a person;
the wall itself renders the set that resolves.

Rasterizing the SVG artwork needs cairosvg (`pip install cairosvg`). Without
it the record still syncs and the PNGs are left as they are -- recorded in
`unresolved`, never silently stale: the record carries each logo's SVG URL,
so a wall built from an un-rasterized entry is visibly missing its logo, not
quietly showing an old one.
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

VOCAB = REPO / "vocab" / "cncf-projects.yaml"
OUT = REPO / "stories" / "cncf-projects.json"
LOGOS = REPO / "assets" / "cncf-logos"
LANDSCAPE_URL = "https://landscape.cncf.io/data/full.json"
LOGO_BASE = "https://landscape.cncf.io/"

# The artwork is composited at this height; wider logos scale down, keeping
# the wordmark legible next to square marks.
LOGO_HEIGHT = 256


def curated_ids(vocab_path=VOCAB):
    """The owner's list, in display order."""
    import yaml

    data = yaml.safe_load(Path(vocab_path).read_text(encoding="utf-8"))
    return list((data or {}).get("projects") or [])


def resolve(ids, landscape):
    """Curated ids -> project records. Unknown ids are reported, not fatal."""
    by_id = {item.get("id"): item for item in landscape.get("items", [])}
    projects, unresolved = [], []
    for pid in ids:
        item = by_id.get(pid)
        if item is None:
            unresolved.append({
                "what": f"curated project {pid!r} is not in the landscape",
                "blocked_on": "the landscape renaming or retiring the project; "
                              "fix vocab/cncf-projects.yaml",
                "automatable": "no",
            })
            continue
        logo = item.get("logo") or ""
        projects.append({
            "id": pid,
            "name": item.get("name") or pid,
            "homepage_url": item.get("homepage_url") or "",
            "logo_svg_url": LOGO_BASE + logo if logo else "",
            "logo_png": f"assets/cncf-logos/{pid}.png" if logo else "",
        })
    return projects, unresolved


def fetch_landscape(url=LANDSCAPE_URL):
    with urllib.request.urlopen(url, timeout=120) as fh:
        return json.loads(fh.read().decode("utf-8"))


def rasterize(svg_bytes, dest, height=LOGO_HEIGHT):
    """SVG artwork -> PNG at a fixed height. Needs cairosvg."""
    import cairosvg

    with tempfile.NamedTemporaryFile(suffix=".svg", delete=False) as tmp:
        tmp.write(svg_bytes)
        tmp_path = tmp.name
    try:
        cairosvg.svg2png(url=tmp_path, write_to=str(dest),
                         output_height=height)
    finally:
        Path(tmp_path).unlink(missing_ok=True)


def record(projects, unresolved):
    return {
        "_what": "The CNCF project set on act III's closing wall, resolved "
                 "from the landscape. GENERATED by scripts/sync_landscape.py "
                 "from vocab/cncf-projects.yaml -- never hand-edit.",
        "_source": LANDSCAPE_URL,
        "projects": projects,
        "unresolved": unresolved,
    }


def sync(write=False, fetch=fetch_landscape, logos_dir=LOGOS, out_path=OUT):
    ids = curated_ids()
    landscape = fetch()
    projects, unresolved = resolve(ids, landscape)

    for project in projects:
        if not project["logo_png"]:
            continue
        dest = Path(logos_dir) / f"{project['id']}.png"
        if write:
            try:
                with urllib.request.urlopen(project["logo_svg_url"],
                                            timeout=60) as fh:
                    svg = fh.read()
                Path(logos_dir).mkdir(parents=True, exist_ok=True)
                rasterize(svg, dest)
            except ImportError:
                unresolved.append({
                    "what": f"{project['id']}: artwork not rasterized -- "
                            "cairosvg is not installed",
                    "blocked_on": "pip install cairosvg, then --write again",
                    "automatable": "yes",
                })
            except Exception as exc:  # noqa: BLE001 -- network/server failure
                unresolved.append({
                    "what": f"{project['id']}: logo fetch failed: {exc}",
                    "blocked_on": "the landscape serving the artwork again",
                    "automatable": "yes",
                })

    doc = record(projects, unresolved)
    text = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
    current = Path(out_path).read_text(encoding="utf-8") \
        if Path(out_path).exists() else None
    if current == text:
        print("stories/cncf-projects.json is current")
        return [], unresolved
    if write:
        Path(out_path).write_text(text, encoding="utf-8")
        print(f"wrote {out_path} ({len(projects)} project(s), "
              f"{len(unresolved)} unresolved)")
        return [], unresolved
    return ["stories/cncf-projects.json"], unresolved


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true",
                    help="write the record and the artwork")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero on drift or an unresolved project")
    args = ap.parse_args(argv)

    drift, unresolved = sync(write=args.write)
    for item in unresolved:
        print(f"UNRESOLVED: {item['what']}", file=sys.stderr)
    if drift:
        print("drift: " + ", ".join(drift) + " -- run --write",
              file=sys.stderr)
    if args.check and (drift or unresolved):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
